### ISSUE TITLE
Why mailer command need to execute select 1

### ISSUE THREAD

**Issue by ekosuhariyadi** [yarcode/yii2-async-mailer#1]
Hi, i'm currently trying to implement your library to my project.
Can i ask question, why in MailerCommand class need to execute SELECT 1 from $app->db?
Actually my app has no database connection, except redis connection that this library needed.

Thanks

**Comment by metalagman** [comment]
@ekosuhariyadi default PDO db connection implementation does not make reconnection on db timeouts. So "SELECT 1" helps us to keep the db connection open.

**Comment by metalagman** [comment]
@ekosuhariyadi so you can just extend MailerCommand and make your own implementation of prepare() without running "SELECT 1".
